### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by kirtyvedula** [vidits-kth/py-itpp#2]
Hi, 

I am trying to clone this repository and implement it on Windows. Is there a way to execute this? Or this specific to Linux? I get the following error. Could you please help with this?

![Screenshot 2019-03-23 11 05 44](https://user-images.githubusercontent.com/4136158/54867867-c55bc800-4d5b-11e9-8154-e683d92eaf7d.png)

**Comment by mohit-madan** [comment]
You can use ubuntu for windows application for this.
Anyways why are you using sudo in windows? its a linux command
